// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCknKH0jaHbesiCaQM2znXYhwDy_DLJG48',
    appId: '1:577731191883:web:6e7d8ceb2d755cf380d9ce',
    messagingSenderId: '577731191883',
    projectId: 'kofitek-app',
    authDomain: 'kofitek-app.firebaseapp.com',
    storageBucket: 'kofitek-app.appspot.com',
    measurementId: 'G-N3T2HM3MVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqWWi-1Ps7yOFzHFD5Ygoth_TXBaEQlKo',
    appId: '1:577731191883:android:37ae36f7df027f2380d9ce',
    messagingSenderId: '577731191883',
    projectId: 'kofitek-app',
    storageBucket: 'kofitek-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGbNlT5Chq_oC6a7xwCdhE58bIPh8SPHA',
    appId: '1:577731191883:ios:1ca6df99afa4e8f980d9ce',
    messagingSenderId: '577731191883',
    projectId: 'kofitek-app',
    storageBucket: 'kofitek-app.appspot.com',
    iosBundleId: 'kofitek.ai.kofitekApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGbNlT5Chq_oC6a7xwCdhE58bIPh8SPHA',
    appId: '1:577731191883:ios:3c43b38c76728d3080d9ce',
    messagingSenderId: '577731191883',
    projectId: 'kofitek-app',
    storageBucket: 'kofitek-app.appspot.com',
    iosBundleId: 'kofitek.ai.kofitekApp.RunnerTests',
  );
}
